// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Publish provides a mock function with given fields: topic, reader
func (_m *Service) Publish(topic string, reader io.Reader) error {
	ret := _m.Called(topic, reader)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, io.Reader) error); ok {
		r0 = rf(topic, reader)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
